name: "spec"

on: [push, pull_request]

jobs:
  # this runs the tests in the docker image against live postgres & mysql
  # and openresty
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    # - uses: leafo/lapis@master

    - name: build
      run: |
        docker build -t lapis-test .

    - name: test
      run: |
        docker run lapis-test


  # this runs all generic lua tests
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: build
      run: |
        curl -O https://raw.githubusercontent.com/leafo/pgmoon/master/pgmoon-dev-1.rockspec
        [[ -z $(comm -12  <(echo "5.1";echo "5.2") <(echo "${{ matrix.luaVersion }}")) ]] && sed -i '/luabitop/d' pgmoon-dev-1.rockspec
        luarocks install pgmoon-dev-1.rockspec
        luarocks install busted
        luarocks install moonscript
        luarocks install https://raw.githubusercontent.com/leafo/lua-cjson/master/lua-cjson-dev-1.rockspec
        luarocks make

    - name: test
      run: |
        busted -o utfTerminal
